### ISSUE TITLE
只写min参数的时候会出现bug

### ISSUE THREAD

**Issue by zaneon** [guguji5/angular-splitter#1]
`<tam-splitter splitterBarWidth=1 [direction]="'horizontal'" [useTransition]="100">
    <tam-splitter-panel [size]="30" [min]="20">
        1
    </tam-splitter-panel>
    <tam-splitter-panel [size]="70">
        2
    </tam-splitter-panel>
</tam-splitter>`

这种情况下可以直接把右边的区域拖到左边覆盖左边导致min不生效

![jietu20181015-112305](https://user-images.githubusercontent.com/6835180/46928368-c9791080-d06c-11e8-8264-161bcfe495f7.png)

**Comment by guguji5** [comment]
试了你的代码，似乎没出现你说的min不生效的情况。你使用什么浏览器，os。你可以用codepen这种即时预览工具，展示一下你说的问题吗？或者来个gif图，video也行。
```
<tam-splitter splitterBarWidth=1 [direction]="'horizontal'" [useTransition]="100">
    <tam-splitter-panel [size]="30" [min]="20"> 1 </tam-splitter-panel>
    <tam-splitter-panel [size]="70"> 2 </tam-splitter-panel>
</tam-splitter>
```
![issue](https://user-images.githubusercontent.com/17986248/46931028-bae62580-d07b-11e8-87ea-3967e1fd60bd.gif)

**Comment by zaneon** [comment]
![jietu20181015-133859-hd](https://user-images.githubusercontent.com/6835180/46931919-d5ba9900-d07f-11e8-9909-bd7c38a1a7b5.gif)

mac  chrome，慢慢拖动到浏览器边缘会发生，快速拖动有时候也会

**Comment by guguji5** [comment]
哈哈，还真会出现，我晚上搞一下。

**Comment by guguji5** [comment]
@Zaneon 改好了，再拉一下代码吧。

**Comment by guguji5** [comment]
似乎没啥问题了，那我就关了哈
